# COMP 352 - Final Project: Footballer Market Evaluation

**Author:** Zevin Attisha, Santi Guerrero, Santiago Pedetti, Christian Vaikona

#### Full dataset: https://www.kaggle.com/datasets/davidcariboo/player-scores/data?select=appearances.csv

## Table of Contents:
* [Environment Setup](#env-setup)
* [Data Importing and Pre-processing](#data-importing)
* [Data Analysis and Visualization](#data-vis)
* [Data Analytics](#data-analytics)

## Environment Setup <a class="anchor" id="env-setup"></a>

(COPIED AND PASTED - EDIT LATER)

First we must setup our environment to make sure we have all appropriate modules installed. To do this, I have provided 2 methods. The 1st, is to install all modules using a ```.yaml``` file via ```conda```. 

To do this, run:
```bash
conda env create -f env_setup/data_environment.yml
```
Then activate the environment by:
```bash
conda activate data_env
```

(COPIED AND PASTED - EDIT LATER)

You can also use the ```requirements.txt``` file to download the modules via ```pip```.

To do this, first make create and activate your environment:
```bash
conda create -n my_data_env
conda activate my_data_env
```

You may need to install setup tools. To do this run (Note you may need to change ```pip3``` to ```pip```):
```bash
pip3 install --upgrade pip setuptools wheel
```

and then run:
```bash
pip3 install -r env_setup/requirements.txt
```

## Data Importing and Pre-processing <a class="anchor" id="data-importing"></a>

Section Overview:

- Import dataset and describe characteristics such as dimensions, data types, file types, and import methods used
- Clean, wrangle, and handle missing data, duplicate data, etc.
- Encode any categorical variables
- Perform feature engineering on the dataset
- Transform data appropriately using techniques such as aggregation, normalization, and feature construction
- Reduce redundant data and perform need based discretization

yolo

In [4]:
# Import libraries needed
import pandas as pd

pd.set_option("display.max_columns", None)
import warnings

# import branca
# import folium
# import geopandas as gpd
# import lightgbm as lgb
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# import xgboost as xgb
# from branca.element import Figure
# from folium import Marker
# from folium.plugins import HeatMap
from scipy.special import boxcox1p
from scipy.stats import norm, probplot, skew
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import ElasticNet, LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor

from utils.model_scripts import (
    hello
)
from utils.metric_scripts import (
    hello
)

warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=FutureWarning, module="pandas.*")
%matplotlib inline

In [5]:
# Read in files
player_valuations_df = pd.read_csv("data/raw/player_valuations.csv")
players_df = pd.read_csv("data/raw/players.csv")

In [6]:
# Dimensions of each df
print("player_valuations.csv dimensions: " + str(player_valuations_df.shape))
print("players.csv dimensions: " + str(players_df.shape))

player_valuations.csv dimensions: (496606, 5)
players.csv dimensions: (32601, 23)

In [7]:
# Count the number of categorical variables

pv_cat_count = 0
for dtype in player_valuations_df.dtypes:
    if dtype == "object":
        pv_cat_count +=1

pv_cat_count += 2 #  because dtypes considered 2 id varibales as ints

pv_numeric_vars = player_valuations_df.shape[1] - pv_cat_count

print("For player_valuations.csv Data:")
print("# of categorical values: " + str(pv_cat_count))
print("# of continuous variables:", str(pv_numeric_vars)+"\n")

p_cat_count = 0
for dtype in players_df.dtypes:
    if dtype == "object":
        p_cat_count +=1

p_numeric_vars = players_df.shape[1] - p_cat_count

print("For players.csv Data:")
print("# of categorical values: " + str(p_cat_count))
print("# of continuous variables:", str(p_numeric_vars)) 

# print(player_valuations_df.dtypes)

# print(players_df.dtypes)

For player_valuations.csv Data:
# of categorical values: 4
# of continuous variables: 1

For players.csv Data:
# of categorical values: 17
# of continuous variables: 6

In [8]:
# Make copies of dfs
player_valuations_df_copy = player_valuations_df.copy()
players_df_copy = players_df.copy()

In [9]:
#merging player_valuations to players
#every row in players will be seen in merged
#matching rows on player_id
#left join
merged_df = players_df_copy.merge(
    player_valuations_df_copy,
    on="player_id",
    how="left",
    suffixes=("_player", "_valuation") #changing names to better identify
)

merged_df.shape
merged_df.head()

#done by zevin

,player_id,first_name,last_name,name,last_season,current_club_id_player,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur_player,highest_market_value_in_eur,date,market_value_in_eur_valuation,current_club_id_valuation,player_club_domestic_competition_id
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,2004-10-04,7000000.0,398.0,IT1
1,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,2005-01-07,9000000.0,398.0,IT1
2,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,2005-05-05,12000000.0,398.0,IT1
3,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,2005-09-30,15000000.0,398.0,IT1
4,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0,2006-01-09,20000000.0,398.0,IT1

In [20]:
#determining the age of players at time of valuation
#done by zevin 
merged_df["date"] = pd.to_datetime(merged_df["date"])
merged_df["date_of_birth"] = pd.to_datetime(merged_df["date_of_birth"])

merged_df["age_at_valuation"] = (
    (merged_df["date"] - merged_df["date_of_birth"])
    .dt.days / 365.25
)

merged_df["date"] = pd.to_datetime(merged_df["date"], errors="coerce")
merged_df["date_of_birth"] = pd.to_datetime(merged_df["date_of_birth"], errors="coerce")

merged_df = merged_df.sort_values(
    ["player_id", "date"]
).reset_index(drop=True)

merged_df.loc[
    merged_df["player_id"] == merged_df["player_id"].iloc[0],
    ["player_id", "date", "market_value_in_eur_valuation"]
].head(10)

   player_id       date  market_value_in_eur_valuation
0         10 2004-10-04                      7000000.0
1         10 2005-01-07                      9000000.0
2         10 2005-05-05                     12000000.0
3         10 2005-09-30                     15000000.0
4         10 2006-01-09                     20000000.0
5         10 2006-07-15                     30000000.0
6         10 2007-06-21                     23000000.0
7         10 2008-06-04                     20000000.0
8         10 2009-06-10                     18000000.0
9         10 2009-08-30                     12000000.0

In [21]:
merged_df[["position", "sub_position", "foot", "current_club_domestic_competition_id"]].head()

  position    sub_position   foot current_club_domestic_competition_id
0   Attack  Centre-Forward  right                                  IT1
1   Attack  Centre-Forward  right                                  IT1
2   Attack  Centre-Forward  right                                  IT1
3   Attack  Centre-Forward  right                                  IT1
4   Attack  Centre-Forward  right                                  IT1

In [27]:
merged_df.columns.tolist()

['player_id',
 'first_name',
 'last_name',
 'name',
 'last_season',
 'current_club_id_player',
 'player_code',
 'country_of_birth',
 'city_of_birth',
 'country_of_citizenship',
 'date_of_birth',
 'height_in_cm',
 'contract_expiration_date',
 'agent_name',
 'image_url',
 'url',
 'current_club_name',
 'market_value_in_eur_player',
 'highest_market_value_in_eur',
 'date',
 'market_value_in_eur_valuation',
 'current_club_id_valuation',
 'player_club_domestic_competition_id',
 'age_at_valuation',
 'position_Defender',
 'position_Goalkeeper',
 'position_Midfield',
 'position_Missing',
 'sub_position_Central Midfield',
 'sub_position_Centre-Back',
 'sub_position_Centre-Forward',
 'sub_position_Defensive Midfield',
 'sub_position_Goalkeeper',
 'sub_position_Left Midfield',
 'sub_position_Left Winger',
 'sub_position_Left-Back',
 'sub_position_Right Midfield',
 'sub_position_Right Winger',
 'sub_position_Right-Back',
 'sub_position_Second Striker',
 'foot_left',
 'foot_right',
 'current_club_domestic_competition_id_DK1',
 'current_club_domestic_competition_id_ES1',
 'current_club_domestic_competition_id_FR1',
 'current_club_domestic_competition_id_GB1',
 'current_club_domestic_competition_id_GR1',
 'current_club_domestic_competition_id_IT1',
 'current_club_domestic_competition_id_L1',
 'current_club_domestic_competition_id_NL1',
 'current_club_domestic_competition_id_PO1',
 'current_club_domestic_competition_id_RU1',
 'current_club_domestic_competition_id_SC1',
 'current_club_domestic_competition_id_TR1',
 'current_club_domestic_competition_id_UKR1']

In [29]:
categorical_cols = [
    "position",
    "sub_position",
    "foot",
    "current_club_domestic_competition_id"
]

merged_df = pd.get_dummies(
    merged_df,
    columns=categorical_cols,
    drop_first=True
)

KeyError: "None of [Index(['position', 'sub_position', 'foot',\n       'current_club_domestic_competition_id'],\n      dtype='object')] are in the [columns]"

In [30]:
merged_df.filter(like="position_").head()

,position_Defender,position_Goalkeeper,position_Midfield,position_Missing,sub_position_Central Midfield,sub_position_Centre-Back,sub_position_Centre-Forward,sub_position_Defensive Midfield,sub_position_Goalkeeper,sub_position_Left Midfield,sub_position_Left Winger,sub_position_Left-Back,sub_position_Right Midfield,sub_position_Right Winger,sub_position_Right-Back,sub_position_Second Striker
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [31]:
# Drop unneccesarry columns in players.csv
players_df_copy.drop(
columns = [
    'last_season',
    'player_code',
    'country_of_birth',
    'city_of_birth',
    'foot',
    'height_in_cm',
    'contract_expiration_date',
    'agent_name',
    'image_url',
    'url',
    'country_of_citizenship'
], 
inplace=True)

KeyError: "['last_season', 'player_code', 'country_of_birth', 'city_of_birth', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'url', 'country_of_citizenship'] not found in axis"

In [ ]:
# check for nulls, etc.
print(player_valuations_df_copy.isna().sum())

player_id              0
date                   0
market_value_in_eur    0
dtype: int64

In [ ]:
print(players_df_copy.isna().sum())

player_id                                  0
first_name                              2062
last_name                                  0
name                                       0
current_club_id                            0
date_of_birth                             47
sub_position                             180
position                                   0
current_club_domestic_competition_id       0
current_club_name                          0
market_value_in_eur                     1523
highest_market_value_in_eur             1523
dtype: int64

In [ ]:
players_df_copy = players_df_copy.dropna(subset = ['first_name','market_value_in_eur','highest_market_value_in_eur','date_of_birth','sub_position'])

players_df_copy.head()

,player_id,first_name,last_name,name,current_club_id,date_of_birth,sub_position,position,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,398,1978-06-09 00:00:00,Centre-Forward,Attack,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,16,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,1091,1981-01-30 00:00:00,Centre-Forward,Attack,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
4,80,Tom,Starke,Tom Starke,27,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,L1,FC Bayern München,100000.0,3000000.0
6,123,Christoph,Metzelder,Christoph Metzelder,33,1980-11-05 00:00:00,Centre-Back,Defender,L1,FC Schalke 04,1500000.0,9500000.0

In [ ]:
# player_valuations.csv

# split by player id



#

## Data Analysis and Visualization <a class="anchor" id="data-vis"></a>

Section Overview:

- Identify categorical, ordinal, and numerical variables within data
- Provide measures of centrality and distribution with visualizations
- Diagnose for correlations between variables and determine independent and dependent variables
- Perform exploratory analysis in combination with visualization techniques to discover patterns and features of interest
- Create visualizations that allow for the discovery of insights in the data

## Data Analytics <a class="anchor" id="data-analytics"></a>

Section Overview:

- Determine the need for a supervised or unsupervised learning method and identify dependent and independent variables
- Choose and provide reasoning for the selected metric or metrics employed to assess your model.
- Train, test, cross validate, and provide performance metrics for model results
- Try multiple different types of algorithms to determine the best model for your dataset
- Analyze your model performance